# server.port=${PORT:8080}

# spring.datasource.url=jdbc:postgresql://ep-noisy-fog-a1chnaai-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_63RoatjmPysn
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA Settings
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=false
# spring.jpa.properties.hibernate.default_schema=scott

# # Jackson
# spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
# spring.jackson.time-zone=UTC